# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCIterate <- function(nIter, old, old_ll, single, burn, N, n) {
    .Call('_ConjointChecks_CCIterate', PACKAGE = 'ConjointChecks', nIter, old, old_ll, single, burn, N, n)
}

